[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --force"]

[phases.build]
cmds = ["npm run build -- --skipLibCheck"]   # or just "tsc --noEmit false" if needed

[start]
cmd = "npm start"